module.exports = {
    string: "\n\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMWNWMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMWWMMMMMMMMMMMMMMMWNNWMMMMMMMMMMMMMMMMWNNWMMWWMMMMMMWW\n\
MMMMNxlOWWklo0WXxokOollllloOWW0o;,;xNMKddKMMNxoOWMMXxlkNMWkclllllllONMM0olllllkNMMNkc;,lKMMKolllllkNMMXxc,;oXM0lclllllxX\n\
MMMMK;'kWK; ;0Wk':Ol......;KXo.... .dNx.cXMMO,;0MMWx..kWMK;...  ..,OMMNo..... 'OW0:... .lNWd..... 'OWk;... .dXl..  ...dW\n\
MMMM0,;KXl..lN0;;0O,,xOOOk0Kc.;x0O:,x0:,OMMNl'xWMWO, ,0MMXOkx:.cOk0NMMO,,xOOl.;0k,'oOO;.:K0;,xOOl.;Ox',d0k,.lK0Ol.;xOOXM\n\
MMMMx.lKo...xK:,ONl.dWWWWMXc'oXMMMK0Nd.lXNNk':XMWO;..;KMMMM0o,;KMWWMWNl'xWMNo.ok,,OWMWd.cKo.lXNKc'dd':KMMNl.oWMXc'kWMMMM\n\
MMMWo.oo,:,'dc,kWO'.,:cOWWd'lNMMMMMM0;..,,,.'kWM0:cl.:XMMMNo..dWNxcoOx'.:ll;.cO:'kWMMNl.xO,..,,',dk,;0MMMK:'OMWk'cXMMMMM\n\
MMMX:.;,lx'';,dWXc....:KM0,,0MMMMMMNo..'''..cXM0::0d.lNMMMO,.:KMO' 'xc... .,dKd.lNMMMO,:0l..''..;Ol.xWMMWx'lNMX:'OMMMMMM\n\
MMM0,..cKx...oNWk':OK0KWWd.lNMMMWNM0,;ONN0;'OWK:.,c'.oWMMNl';xWW0xdkd';kl.,0MK:'kMMMK:,kk':0NXx.;d,,0MMWO,;0MWx'lNMMMMMM\n\
MMMk..:KNl..lXMX:'OMMMWWXc.cXMW0oONl'xWMWx'lNKc,::;..dWMMk':OXMMMMMK:'OWk.;KMO'.kMWO;'xKc'kWMNo.od.,0MNk,,kWMK;,OMMMMMMM\n\
MMWo.;0MX:.cXMWx..clllo0Xc..;c;.,OO':XMMK;,OKc;OWWX:.xMMXc'kWWMMMMWx'lNMk.;KMO'.'c:.'xNk..:ll;.cKx..,c;.;OWMWd.oNMMMMMMM\n\
MM0;.xWWk''OMM0;......:XWk'  .,oKKc.xWMNo.cOc'xWMWO,'kMWx':XMMMMMM0;,OMWd.,OMXl. ..c0WK:.....'oXMK:. .'oKMMWO,,OMMMMMMMM\n\
MMXOOXMWKO0NMMXOkkkkkk0WMWKxxOXWMXOOXMMN0OKXOONMMWKOOXMW0OKWMMMMMWXO0NMWKOOXMMNOxkKWMMXOkkOOOXWMMMXkxkXWMMMWKO0NMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\n"
}